import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr';

type LanguageContextValue = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const translations = {
  en: {
    // Header
    appName: 'CAFE DE LA PLACE',
    financialDashboard: 'Financial Dashboard',
    
    // Tabs
    dashboard: 'Dashboard',
    revenue: 'Revenue',
    reports: 'Reports',
    documents: 'Documents',
    
    // Sidebar
    employees: 'Employees',
    addEmployee: 'Employee',
    noEmployees: 'No employees',
    salary: 'Salary',
    contributions: 'Contributions',
    logout: 'Logout',
    newSession: 'New Session',
    sessions: 'Sessions',
    allSessions: 'All Sessions',
    clearAll: 'Clear All',
    resetAllData: 'Reset All Data',
    resetView: 'Reset View',

    /** Theme toggle (floating control; visible on /app and marketing pages) */
    themeAriaLight: 'Switch to light theme',
    themeAriaDark: 'Switch to dark theme',
    themeTitleLight: 'Light mode',
    themeTitleDark: 'Dark mode',
    themeLabelLight: 'Light',
    themeLabelDark: 'Dark',
    
    // Financial Summary
    income: 'Income',
    expenses: 'Expenses',
    payroll: 'Payroll',
    balance: 'Balance',
    
    // Income
    incomeTitle: 'Income',
    addIncome: 'Add',
    noIncome: 'No income recorded',
    sales: 'Sales',
    reservation: 'Reservations',
    
    // Expenses
    expensesTitle: 'Expenses',
    addExpense: 'Add',
    noExpenses: 'No expenses recorded',
    bills: 'Bills (electricity, rent...)',
    suppliers: 'Suppliers',
    payrollCategory: 'Payroll',
    other: 'Other',
    
    // Modals
    addEmployeeTitle: 'Add Employee',
    addIncomeTitle: 'Add Income',
    addExpenseTitle: 'Add Expense',
    name: 'Name',
    position: 'Position',
    monthlySalary: 'Monthly Salary (CHF)',
    socialContributions: 'Social Contributions (CHF)',
    date: 'Date',
    type: 'Type',
    amount: 'Amount (CHF)',
    description: 'Description',
    category: 'Category',
    add: 'Add',
    cancel: 'Cancel',
    
    // Types
    SALES: 'Sales',
    RESERVATION: 'Reservations',
    BILLS: 'Bills',
    SUPPLIERS: 'Suppliers',
    PAYROLL: 'Payroll',
    OTHER: 'Other',
    // Landing - Navbar
    navFeatures: 'Features',
    navHowItWorks: 'How It Works',
    navModules: 'Modules',
    navPlatform: 'Platform',
    navPricing: 'Pricing',
    navSecurity: 'Security',
    navContact: 'Contact',
    navGetStarted: 'Get Started',
    navSwitchToFrench: 'Switch to French',
    navSwitchToEnglish: 'Switch to English',
    navChangeLanguage: 'Change Language',
    /** Navbar: one-click toggle to the other language */
    navTranslateEnglish: 'English',
    navTranslateFrench: 'Français',

    // Landing - Hero
    heroBadge: 'Built for Switzerland',
    heroTitleLine1: 'Your Finances,',
    heroTitleHighlight: 'Automated',
    heroTitleLine2: 'with Swiss Precision',
    heroDescription:
      'Upload any document - invoice, receipt, payslip - and let AI extract, categorize, and organize your financial data. Income, expenses, salaries, and reports in one platform.',
    heroStartTrial: 'Start Free Trial',
    heroWatchDemo: 'Watch Demo',
    heroStatAccuracy: 'OCR Accuracy',
    heroStatSpeed: 'Faster Processing',
    heroStatBusinesses: 'Businesses',
    heroImageAlt:
      'Paystack.ch Financial Dashboard showing income, expenses, salary summaries and AI document processing',
    heroDocumentProcessed: 'Document Processed',
    heroExtractedAmount: "CHF 2'486.63 extracted",

    // Landing - Pricing
    pricingTitle: 'Pricing',
    pricingHeadingStart: 'Simple, transparent',
    pricingHeadingHighlight: 'pricing',
    pricingDescription:
      'All prices in CHF. Start with a 7-day trial (payment method on file), then recurring billing. Scale as your business grows.',
    pricingMostPopular: 'Most Popular',
    pricingCurrency: 'CHF',
    pricingCustom: 'Custom',
    pricingStarterAmount: '29.-',
    pricingBusinessAmount: '59.-',
    pricingUnlimitedAmount: '499.-',
    pricingPerMonth: '/month',
    planStarterName: 'Starter',
    planStarterDescription:
      'For freelancers and solo entrepreneurs getting started with financial automation.',
    planBusinessName: 'Business',
    planBusinessDescription:
      'For growing businesses that need full financial management with team access.',
    planUnlimitedName: 'Unlimited',
    planUnlimitedDescription:
      'For high-volume teams: every in-app module, no document cap, full Swiss reporting, and self-serve billing.',
    planEnterpriseName: 'Enterprise',
    planEnterpriseDescription:
      'For large organizations requiring custom integrations, SLA, and dedicated support.',
    planStarterFeature1: 'Document Processing (50/mo)',
    planStarterFeature2: 'Income & Expense Tracking',
    planStarterFeature3: 'Dashboard CHF totals; Reports tab with filters, monthly breakdown & CSV export',
    planStarterFeature4: '1 User',
    planStarterFeature5: 'Email Support',
    planStarterFeature6: 'Up to 2 saved sessions (your accounting periods)',
    planBusinessFeature1: 'Document Processing (500/mo)',
    planBusinessFeature2: 'Revenue tab: POS / Z-readings, payroll & up to 10 employees',
    planBusinessFeature3: 'PDF reports & Swiss TVA exports (CSV/PDF, by month or year)',
    planBusinessFeature4: 'Up to 10 Users',
    planBusinessFeature5: 'Unlimited sessions + “All sessions” consolidated totals',
    planBusinessFeature6: 'Priority Support',
    planBusinessFeature7: 'Stripe customer portal (plan, card, cancel)',
    planUnlimitedFeature1: 'Unlimited Document Processing',
    planUnlimitedFeature2: 'Unlimited Users',
    planUnlimitedFeature3: 'All Modules (Current + Future)',
    planUnlimitedFeature4: 'Full PDF & Swiss TVA reporting (same as Business, no doc cap)',
    planUnlimitedFeature5: 'Unlimited sessions, employees & “All sessions” view',
    planUnlimitedFeature6: 'Self-serve billing & upgrades via Stripe (no doc cap)',
    planEnterpriseFeature1: 'White Label Option',
    planEnterpriseFeature2: 'Unlimited Document Processing',
    planEnterpriseFeature3: 'Custom Integration',
    planEnterpriseFeature4: 'All Modules (Current + Future)',
    planEnterpriseFeature5: 'Unlimited Users',
    planEnterpriseFeature6: 'Dedicated Account Manager',
    planEnterpriseFeature7: 'SLA & Uptime Guarantee',
    planEnterpriseFeature8: 'On-premise Deployment',
    ctaStartTrial: 'Start Free Trial',
    ctaContactSales: 'Contact Sales',

    // Landing - CTA section
    ctaSectionLabel: 'Get Started',
    ctaSectionHeadingStart: 'Ready to automate',
    ctaSectionHeadingHighlight: 'your finances?',
    ctaSectionDescription:
      'Join Swiss businesses that have already transformed their financial management. Start with a 7-day trial, then continue with a simple subscription.',
    ctaSectionBookDemo: 'Book a Demo',
    ctaSectionTrust1: '7-day trial',
    ctaSectionTrust2: 'Secure billing via Stripe',
    ctaSectionTrust3: 'Cancel anytime',
    ctaSectionContactUs: 'Contact Us',
    contactEmail: 'Email',
    contactPhone: 'Phone',
    contactLocation: 'Location',
    contactCityCountry: 'Geneva, Switzerland',
    swissMadeGeneva: 'Swiss Made Software - Geneva, CH',

    // Auth pages
    authTagline: 'Financial tracking',
    authSignInTitle: 'Sign in',
    authSignUpTitle: 'Create account',
    authDisplayName: 'Display name',
    authEmailLabel: 'Email',
    authPasswordLabel: 'Password',
    authContinueGoogle: 'Continue with Google',
    authSubmitSignIn: 'Sign in',
    authSubmitSignUp: 'Create account',
    authAdminTitle: 'Admin sign in',
    authAdminDescription: 'Admin access for existing Paystack.ch operators. No payment checkout required.',
    authAdminSubmit: 'Sign in as admin',
    authAdminGoogle: 'Continue as admin with Google',
    authAdminUnauthorized: 'This account is not configured as a Paystack.ch admin.',
    authAdminGateTitle: 'Operator access',
    authAdminGateDescription:
      'Enter the server password set as ADMIN_ACCESS_PASSWORD in Vercel to unlock plan checkout tools.',
    authAdminGatePasswordLabel: 'Server password',
    authAdminGateSubmit: 'Unlock tools',
    authAdminGateLock: 'Lock admin',
    authAdminPlanTestTitle: 'Open guest checkout by plan',
    authAdminPlanLive: 'Live Stripe (real keys)',
    authAdminPlanTest: 'Test Stripe (test keys)',
    authAdminBypassSectionTitle: 'Firebase admin (subscription bypass)',
    authNeedAccount: "Don't have an account?",
    authSignUpLink: 'Sign up',
    authHaveAccount: 'Already have an account?',
    authSignInLink: 'Sign in',
    authBackHome: 'Back to home',
    authFooterSecure: 'Secure access · Your data stays yours',
    authWorking: 'Please wait…',
    authFirebaseMissingShort: 'Firebase is not configured. Add VITE_FIREBASE_* to your environment.',
    checkoutSameEmailNote:
      'Payment method saved. Create your account using the same email you entered at checkout so your subscription links to this login.',
    navSignInExisting: 'Admin login',
    checkoutLinkErrorTitle: 'Could not link your subscription',
    checkoutTryAgain: 'Try again',
    checkoutContinueWithoutLink: 'Continue to app',

    // Pre-login Stripe checkout (/start-trial)
    startTrialTitle: 'Start your 7-day trial',
    startTrialSubtitle: 'Secure checkout',
    startTrialBody:
      'Add a payment method to start your trial. Billing begins after the trial unless you cancel in the customer portal. Then create or sign in with the same email.',
    startTrialBillingNote:
      'Use the same email for your Paystack.ch account as at Stripe checkout so your subscription attaches correctly.',
    startTrialCta: 'Continue to secure checkout',
    startTrialSignIn: 'Already have an account?',
    startTrialRedirecting: 'Redirecting to secure checkout…',
    startTrialCheckoutCancelled: 'Checkout was cancelled',
    startTrialCheckoutCancelledHint: 'You can go home or start checkout again for this plan.',
    startTrialGoHome: 'Back to home',
    startTrialRetry: 'Try checkout again',

    subscriptionLoading: 'Checking subscription…',
    subscriptionTitle: 'Subscribe to continue',
    subscriptionBody:
      'Your workspace requires an active plan. Start a 7-day trial (card required today), then you are billed automatically when the trial ends unless you cancel in the billing portal.',
    subscriptionCta: 'Start 7-day trial & subscribe',
    subscriptionUpdatePayment: 'Update payment method',
    subscriptionTrialUntil: 'Trial access until {date}',
    subscriptionManageBilling: 'Billing & plan',
    subscriptionPickPlan: 'Choose a plan',
    subscriptionEnterpriseHint: 'Enterprise (custom pricing): contact sales at info@paystack.ch.',
    subscriptionPickPlanError: 'Please choose Starter, Business, or Unlimited before continuing to checkout.',
    planLimitDocuments: 'Monthly document processing limit reached ({n} completed this month). Upgrade your plan to process more.',
    planLimitSessions: 'Your plan allows up to {n} accounting periods (sessions). Upgrade to add more.',
    planLimitEmployees: 'Your plan allows up to {n} employee slot(s). Upgrade to add more.',
    reportsAdvancedLocked: 'Advanced PDF exports and Swiss TVA statements require Business or higher.',

    planSummaryTitle: 'Your subscription',
    planSummaryPlanUnknown: 'Plan',
    planSummaryUnlimited: 'Unlimited',
    planSummaryStatusTrialing: 'Trial',
    planSummaryStatusActive: 'Active',
    planSummaryDocuments: 'Documents / month',
    planSummaryEmployees: 'Team slots',
    planSummarySessions: 'Saved sessions',
    planSummaryFlagBasicReports: 'Reports & CSV',
    planSummaryFlagAdvanced: 'Advanced analytics & Swiss reporting',
    planSummaryFlagAllModules: 'All core modules',
    planSummaryFlagApi: 'API access',
    planSummaryFlagPriority: 'Priority support',

    authDividerEmail: 'Email',
    authPlaceholderAdminEmail: 'admin@paystack.ch',
    authPlaceholderEmail: 'you@company.ch',
    authPlaceholderDisplayName: 'Marie Mueller',
    authErrorPrefix: 'Error: ',

    footerTagline:
      'AI-powered financial management built with Swiss precision. Trusted by businesses across Switzerland.',
    footerSwissSoftware: 'Swiss software',
    footerCopyright: 'Paystack.ch — All rights reserved.',
    footerTrustGdpr: 'GDPR-ready',
    footerTrustSwissDp: 'Swiss data protection',
    footerTrustSoc2: 'SOC 2-ready',
    footerColProduct: 'Product',
    footerColCompany: 'Company',
    footerColResources: 'Resources',
    footerColLegal: 'Legal',
    footerProduct1: 'Features',
    footerProduct2: 'Pricing',
    footerProduct3: 'Modules',
    footerProduct4: 'Roadmap',
    footerProduct5: 'Changelog',
    footerCompany1: 'About',
    footerCompany2: 'Careers',
    footerCompany3: 'Blog',
    footerCompany4: 'Press kit',
    footerResources1: 'Documentation',
    footerResources2: 'API reference',
    footerResources3: 'Help center',
    footerResources4: 'Community',
    footerLegal1: 'Privacy policy',
    footerLegal2: 'Terms of use',
    footerLegal3: 'Data processing',
    footerLegal4: 'Legal notice',

    landingSection01Label: 'Core features',
    landingFeaturesTitle1: 'Everything you need to',
    landingFeaturesTitleItalic: 'run your finances',
    landingFeaturesSubtitle:
      'Six powerful modules work together to automate your financial operations. Enable only what your business needs.',
    landingFeat1Title: 'AI document processing',
    landingFeat1Desc:
      'Upload invoices, receipts, bank statements, or payslips in any format. Our AI extracts data with 95%+ accuracy, automatically categorizes entries, and detects duplicates — turning paper into structured financial data in seconds.',
    landingFeat1S1L: 'Accuracy',
    landingFeat1S1V: '95%+',
    landingFeat1S2L: 'Formats',
    landingFeat1S2V: 'PDF, JPG, PNG',
    landingFeat1S3L: 'Processing',
    landingFeat1S3V: '3x parallel',
    landingFeat2Title: 'Revenue tracking',
    landingFeat2Desc:
      'Track every revenue stream — from daily sales and service fees to subscriptions and commissions. Automatic income creation from processed documents with real-time dashboard updates and period-based organization.',
    landingFeat2S1L: 'Categories',
    landingFeat2S1V: 'Unlimited',
    landingFeat2S2L: 'Updates',
    landingFeat2S2V: 'Real time',
    landingFeat2S3L: 'Sources',
    landingFeat2S3V: 'Auto + manual',
    landingFeat3Title: 'Expense management',
    landingFeat3Desc:
      'Comprehensive multi-category expense tracking organized by supplier. From rent and utilities to payroll and marketing — every franc is accounted for with automatic expense creation from uploaded documents.',
    landingFeat3S1L: 'Categories',
    landingFeat3S1V: '12+ built-in',
    landingFeat3S2L: 'Tracking',
    landingFeat3S2V: 'By supplier',
    landingFeat3S3L: 'Export',
    landingFeat3S3V: 'Excel + PDF',
    landingFeat4Title: 'Payroll & salaries',
    landingFeat4Desc:
      'Process employee payslips with Swiss-format support including AVS, LPP, and AC deductions. Track gross and net salaries, manage deduction breakdowns, and generate monthly payroll summaries automatically.',
    landingFeat4S1L: 'Format',
    landingFeat4S1V: 'Swiss (AVS/LPP)',
    landingFeat4S2L: 'Deductions',
    landingFeat4S2V: 'Customizable',
    landingFeat4S3L: 'Reports',
    landingFeat4S3V: 'Monthly',
    landingFeat5Title: 'Sessions & periods',
    landingFeat5Desc:
      'Create unlimited accounting periods — daily, weekly, monthly, quarterly, or project-based. Switch between periods instantly, maintain data isolation, and generate period-specific reports for any timeframe.',
    landingFeat5S1L: 'Periods',
    landingFeat5S1V: 'Unlimited',
    landingFeat5S2L: 'Types',
    landingFeat5S2V: '7+ options',
    landingFeat5S3L: 'Switching',
    landingFeat5S3V: 'Instant',
    landingFeat6Title: 'Reports & analytics',
    landingFeat6Desc:
      'Monthly revenue analysis, income vs. expense breakdowns, top supplier insights, and advanced filtering. Export print-ready PDF reports or CSV data with complete audit trails for compliance.',
    landingFeat6S1L: 'Report types',
    landingFeat6S1V: '7+',
    landingFeat6S2L: 'Filters',
    landingFeat6S2V: 'Advanced',
    landingFeat6S3L: 'Export',
    landingFeat6S3V: 'CSV + PDF',

    landingHowLabel: 'How it works',
    landingHowTitle1: 'From paper to',
    landingHowTitleHighlight: 'structured data',
    landingHowTitleSub: 'in four simple steps',
    landingHowStep1Title: 'Import',
    landingHowStep1Sub: 'Capture any document',
    landingHowStep1Desc:
      'Snap a photo, upload a PDF, or drag-and-drop any financial document. Invoices, receipts, bank statements, payslips — we handle them all.',
    landingHowStep2Title: 'Extract',
    landingHowStep2Sub: 'AI reads and understands',
    landingHowStep2Desc:
      'Our AI engine processes your document with 95%+ OCR accuracy, extracting amounts, dates, vendors, categories, and line items automatically.',
    landingHowStep3Title: 'Verify',
    landingHowStep3Sub: 'Data is organized and validated',
    landingHowStep3Desc:
      'Review extracted data in a clean interface. Edit if needed, approve, and the system automatically categorizes entries into income, expenses, or payroll.',
    landingHowStep4Title: 'Report',
    landingHowStep4Sub: 'Ready for your systems',
    landingHowStep4Desc:
      'Access real-time dashboards, generate reports, export to Excel or PDF. Your financial data is structured, searchable, and audit-ready.',
    landingHowScreenshotAlt: 'Paystack.ch — dashboard and document processing',

    landingTrustedLabel: 'Used across industries',
    landingTrustedInd1: 'Retail',
    landingTrustedInd2: 'Restaurants & hospitality',
    landingTrustedInd3: 'Professional services',
    landingTrustedInd4: 'Consulting & freelance',
    landingTrustedInd5: 'Manufacturing',
    landingTrustedInd6: 'Healthcare',
    landingTrustedInd7: 'E-commerce',
    landingTrustedInd8: 'Education',

    landingModulesLabel: 'Modular architecture',
    landingModulesTitle1: 'Enable what you',
    landingModulesTitleItalic: 'actually need',
    landingModulesSubtitle:
      'Every business is different. Turn on only the modules you need — from document processing to full financial management.',
    landingModulesTabCore: 'Core',
    landingModulesTabEnhanced: 'Enhanced',
    landingModuleStatusLive: 'Live',
    landingModuleStatusPartial: 'Partial',
    landingModuleStatusSoon: 'Soon',
    landingModCore1Name: 'Document processing',
    landingModCore1Desc: 'AI-assisted extraction from any format',
    landingModCore2Name: 'Revenue tracking',
    landingModCore2Desc: 'Multi-category tracking with automatic creation',
    landingModCore3Name: 'Expense management',
    landingModCore3Desc: 'Supplier-based expense classification',
    landingModCore4Name: 'Payroll & salaries',
    landingModCore4Desc: 'Swiss payslip processing (AVS/LPP)',
    landingModCore5Name: 'Session management',
    landingModCore5Desc: 'Unlimited accounting periods with instant switching',
    landingModCore6Name: 'Reports & analytics',
    landingModCore6Desc: 'Full financial reports with export options',
    landingModEnh1Name: 'Document library',
    landingModEnh1Desc: 'Entity-based archive with search and filters',
    landingModEnh2Name: 'POS module',
    landingModEnh2Desc: 'Z-reading entry with AI extraction; full POS coming soon',
    landingModEnh3Name: 'Inventory',
    landingModEnh3Desc: 'FIFO/LIFO stock and barcode scanning',
    landingModEnh4Name: 'Employee management',
    landingModEnh4Desc: 'Employee profiles, attendance, and leave',
    landingModEnh5Name: 'Supplier management',
    landingModEnh5Desc: 'Supplier profiles, terms, and performance tracking',
    landingModEnh6Name: 'Invoice generation',
    landingModEnh6Desc: 'Templates, auto numbering, and recurring invoices',
    landingModulesScreenshotAlt: 'Paystack.ch — financial reports and analytics',

    landingBizLabel: 'Industry presets',
    landingBizTitle1: 'Configured for',
    landingBizTitleHighlight: 'your sector',
    landingBizSubtitle:
      'Predefined setups for each type of business. Start from an industry template, then adapt modules to your real workflow.',
    landingBiz1Name: 'Retail',
    landingBiz1Mods: 'POS, Inventory, Income, Expenses, Suppliers',
    landingBiz1Desc: 'Daily sales tracking, stock management, and supplier organization for retail stores.',
    landingBiz2Name: 'Restaurants & cafés',
    landingBiz2Mods: 'POS, Income, Expenses, Payroll, Suppliers',
    landingBiz2Desc: 'Z-reading processing, daily revenue tracking, and staff payroll management.',
    landingBiz3Name: 'Professional services',
    landingBiz3Mods: 'Income, Expenses, Payroll, Projects, Invoicing',
    landingBiz3Desc: 'Project-based accounting, client billing, and contractor payment management.',
    landingBiz4Name: 'Consulting & freelance',
    landingBiz4Mods: 'Income, Expenses, Clients, Projects, Invoicing',
    landingBiz4Desc: 'Client-specific periods, project profitability tracking, and invoice generation.',
    landingBiz5Name: 'Manufacturing',
    landingBiz5Mods: 'Expenses, Payroll, Inventory, Suppliers, Employees',
    landingBiz5Desc: 'Raw material tracking, production cost analysis, and workforce management.',
    landingBiz6Name: 'E-commerce',
    landingBiz6Mods: 'Income, Expenses, Inventory, Suppliers, Integrations',
    landingBiz6Desc: 'Multi-channel revenue tracking, stock synchronization, and platform integrations.',
    landingBiz7Name: 'Healthcare',
    landingBiz7Mods: 'Income, Expenses, Payroll, Employees, Documents',
    landingBiz7Desc: 'Patient billing, staff management, and compliance-ready document archiving.',
    landingBiz8Name: 'Education',
    landingBiz8Mods: 'Income, Expenses, Payroll, Employees, Reports',
    landingBiz8Desc: 'Tuition tracking, staff payroll, and period-based financial reporting.',

    landingPlatformLabel: 'Platform tour',
    landingPlatformTitle1: 'See it',
    landingPlatformTitleItalic: 'in action',
    landingPlatformSubtitle:
      'Real screenshots from a production deployment — not mockups. This is the platform Swiss businesses use today.',
    landingPlatformV1Label: 'Dashboard',
    landingPlatformV1Title: 'Financial overview at a glance',
    landingPlatformV1Desc:
      'See your complete financial picture — revenue, expenses, salaries, and balance — updated in real time. Upload documents directly, track processing status, and monitor VAT in one unified view.',
    landingPlatformV1Alt:
      'Paystack.ch Dashboard — financial overview with revenue, expenses, salaries, VAT tracking, and document upload queue',
    landingPlatformV2Label: 'Revenue & POS',
    landingPlatformV2Title: 'Income tracking & Z-readings',
    landingPlatformV2Desc:
      'Track all revenue streams with auto-generated Z-readings from daily income data. Supports manual entry, photo upload, and AI auto-generation with Swiss VAT calculation (7.7%) and payment split estimation.',
    landingPlatformV2Alt:
      'Paystack.ch Revenue module — Z-reading generation with auto-generate, manual entry, and photo upload options',
    landingPlatformV3Label: 'Reports',
    landingPlatformV3Title: 'Monthly revenue analysis',
    landingPlatformV3Desc:
      'Filter by date range, category, or supplier. View monthly breakdowns of income vs. expenses with balance calculations. Export filtered data as CSV or print-ready PDF reports for your accountant.',
    landingPlatformV3Alt:
      'Paystack.ch Reports — monthly revenue analysis with income, expenses, and balance breakdown per period',
    landingPlatformV4Label: 'Documents',
    landingPlatformV4Title: 'Organized document library',
    landingPlatformV4Desc:
      'All processed documents organized by supplier, employee, or POS report. See document counts and total amounts per entity at a glance. Search, filter, and drill into any supplier\'s complete history.',
    landingPlatformV4Alt:
      'Paystack.ch Document Library — supplier cards showing document counts and total amounts in CHF',
    landingPlatformWlTitle: 'White-label ready',
    landingPlatformWlBody:
      'Each deployment can be tailored to your business — logo, colors, and domain. This example shows a live deployment for Café de la Place.',

    landingSecurityLabel: 'Security & compliance',
    landingSecurityTitle1: 'Security at',
    landingSecurityTitleHighlight: 'Swiss standards',
    landingSecuritySubtitle:
      'Your financial data deserves bank-grade protection. We combine enterprise security with Swiss precision.',
    landingSec1Title: 'End-to-end encryption',
    landingSec1Desc: 'All data is encrypted in transit and at rest using AES-256 encryption standards.',
    landingSec2Title: 'Role-based access',
    landingSec2Desc: 'Granular permissions ensure team members only see what they need to see.',
    landingSec3Title: 'Audit log',
    landingSec3Desc: 'Every action is logged with timestamps for complete traceability and compliance.',
    landingSec4Title: 'Data hosted in Switzerland',
    landingSec4Desc: 'Your financial data stays in Switzerland, compliant with Swiss data protection laws.',
    landingSec5Title: 'Automatic backups',
    landingSec5Desc: 'Continuous backups with disaster recovery ensure your data is never lost.',
    landingSec6Title: 'GDPR-ready',
    landingSec6Desc: 'Full compliance with European data protection regulations and Swiss FADP.',

    landingMobileLabel: 'Mobile app',
    landingMobileTitle1: 'Your finances,',
    landingMobileTitleItalic: 'in your pocket',
    landingMobileSubtitle:
      'The Paystack.ch mobile app brings full financial management to your phone. Scan a receipt, check your dashboard, and approve expenses anywhere.',
    landingMobileF1Label: 'Photo & import',
    landingMobileF1Desc: 'Snap a document and process it instantly',
    landingMobileF2Label: 'Push notifications',
    landingMobileF2Desc: 'Real-time alerts for documents and reports',
    landingMobileF3Label: 'Offline mode',
    landingMobileF3Desc: 'Capture offline; sync when you are back online',
    landingMobileF4Label: 'Native experience',
    landingMobileF4Desc: 'iOS and Android apps with biometric sign-in',
    landingMobileCta: 'Join the waitlist',
    landingMobileTarget: 'Target: Q3 2026',

    landingRoadmapLabel: 'Roadmap',
    landingRoadmapTitle1: 'Built for the',
    landingRoadmapTitleHighlight: 'long term',
    landingRoadmapSubtitle:
      'Our roadmap evolves with customer needs. From essential financial management to enterprise capabilities, we are building a complete platform.',
    landingRoadP1Label: 'Phase 1',
    landingRoadP1Title: 'Core features',
    landingRoadP1I1: 'Document processing',
    landingRoadP1I2: 'Income & expense tracking',
    landingRoadP1I3: 'Session management',
    landingRoadP1I4: 'Basic reports',
    landingRoadP1I5: 'Authentication',
    landingRoadP2Label: 'Phase 2',
    landingRoadP2Title: 'Enhanced features',
    landingRoadP2I1: 'Advanced analytics',
    landingRoadP2I2: 'Inventory tracking',
    landingRoadP2I3: 'Employee management',
    landingRoadP2I4: 'Supplier management',
    landingRoadP3Label: 'Phase 3',
    landingRoadP3Title: 'Advanced features',
    landingRoadP3I1: 'Client management',
    landingRoadP3I2: 'Project management',
    landingRoadP3I3: 'Invoice generation',
    landingRoadP3I4: 'Mobile apps',
    landingRoadP4Label: 'Phase 4',
    landingRoadP4Title: 'Enterprise features',
    landingRoadP4I1: 'Multi-entity support',
    landingRoadP4I2: 'Advanced integrations',
    landingRoadP4I3: 'Custom workflows',
    landingRoadP4I4: 'API marketplace',

    dashFinancialTracking: 'Financial tracking',
    dashSwitchClientTitle: 'Switch client',
    dashSignOutTitle: 'Sign out',
    dashTabReconciliation: 'Reconciliation',
    dashTabInsights: 'Insights',
    dashTitleReconciliation: 'Reconciliation dashboard',
    dashTitleInsights: 'Financial insights',
    dashSubtitleAudit: 'Automated extraction for financial reconciliation.',
    dashSubtitleInsights: 'Multi-modal analysis on audited data.',
    dashFooterCopyright: 'Cafe de la Place • Financial tracking',
    dashFooterZ2: 'Z2 processing',
    dashFooterAuditTrail: 'Audit trail',

    onboardLoading: 'Loading clients…',
    onboardSubtitle: 'Select or add a client',
    onboardHeading: 'Client',
    onboardNewClientLabel: 'New client name',
    onboardPlaceholder: 'e.g. Acme Corp',
    onboardAdd: 'Add',
    onboardSelectExisting: 'Or select an existing client',
    onboardErrorAddClient: 'Failed to add client. Check Firestore rules or console for details.',

    firebaseMissingTitle: 'Firebase configuration missing',
    firebaseMissingBody:
      'This app needs VITE_FIREBASE_* in the frontend environment and GEMINI_API_KEY only on the API server.',
    firebaseMissingNetlifyHeading: 'On Netlify',
    firebaseMissingNetlifyBody:
      'Site settings → Environment variables → add the keys listed in .env.example, then redeploy.',
    firebaseMissingLocalHeading: 'Locally',
    firebaseMissingLocalBody: 'Copy .env.example to .env.local and fill in the values.',
    firebaseMissingCta: 'Open Firebase console',

    emailVerifyTitle: 'Email verification',
    emailVerifyBody: 'Your email and password account is not verified yet.',
    emailVerifySentPrefix: 'A message was sent to',
    emailVerifyResend: 'Resend verification email',
    emailVerifyResending: 'Sending…',
    emailVerifySignOut: 'Sign out',
    emailVerifySuccess: 'Verification email sent. Check your inbox, then reload this page.',

    fiEvidenceMeta: 'Audit Evidence Metadata',
    fiOpenTraceTab: 'Open trace in new tab',
    fiControlMeta: 'Control metadata',
    fiClassification: 'Classification',
    fiFiscalDate: 'Fiscal date',
    fiGrossValue: 'Gross value',
    fiComplianceAlerts: 'Compliance alerts',
    fiAuditIntegrity: 'Audit integrity valid',
    fiAiInterpretation: 'AI interpretation note',
    fiNoInterpretation: 'No diagnostic interpretation trace recorded for this audit asset.',
    fiCloseRecord: 'Close record',
    fiIncomeLabel: 'Money in',
    fiExpenseLabel: 'Money out',
    fiLineCountLabel: 'Audit line count',
    fiAssetsSuffix: 'ASSETS',
    fiRecoStatusLabel: 'Reconciliation status',
    fiCertified: 'CERTIFIED',
    fiDynamicDist: 'Dynamic distribution',
    fiForensicHub: 'Forensic neural hub',
    fiDataIntegration: 'Data integration',
    fiCustomTaxonomy: 'Support custom taxonomy',
    fiChatEmptyTitle: 'Neural engine initialized',
    fiChatEmptyHint: 'Inquire about anomalies, categories, or audit reconciliation',
    fiAnalyzing: 'Running analysis…',
    fiInputPlaceholder: 'Ask about the audited dataset or attach visual evidence…',
    fiUncategorized: 'Uncategorized',
    fiCategoryBank: 'Bank',
    fiUnknownEntity: 'Unknown entity',
    fiAuditVisionScan: '[Audit vision scan]',
    fiModelFailed: 'No response.',
    fiDiagnosticError: 'Diagnostic error: ',
    fiNa: 'N/A',

    bankWorkbenchTitle: 'Reconciliation workbench',
    bankWorkbenchSubtitle: 'Automated matching with audit evidence.',
    bankUploadLabel: 'Upload statements for batch linkage',
    bankStopLinking: 'Stop linking',
    bankStopping: 'Stopping…',
    bankTurboLinking: 'Turbo linking',
    bankWorkersDraining: 'Draining workers',
    bankWorkersActive: '6 active workers',
    bankQueueTitle: 'Statement queue',
    bankMoneyIn: 'Money in',
    bankMoneyOut: 'Money out',
    bankNetCashFlow: 'Net cash flow',
    bankThDate: 'Date',
    bankThDesc: 'Description',
    bankThAmount: 'Amount',
    bankThLinking: 'Audit linking',
    bankNone: 'None',
    bankSelectCompleted: 'Select a completed analysis',
    bankNotifHalting: 'Halting reconciliation…',
    bankVerifiedPrefix: 'Verified: ',
    bankStatus_pending: 'pending',
    bankStatus_processing: 'processing',
    bankStatus_completed: 'completed',
    bankStatus_error: 'error',
    appLoading: 'Loading…',
  },
  fr: {
    // Header
    appName: 'CAFE DE LA PLACE',
    financialDashboard: 'Tableau de bord financier',
    
    // Tabs
    dashboard: 'Tableau de bord',
    revenue: 'Revenus',
    reports: 'Rapports',
    documents: 'Documents',
    
    // Sidebar
    employees: 'Employés',
    addEmployee: 'Employé',
    noEmployees: 'Aucun employé',
    salary: 'Salaire',
    contributions: 'Cotisations',
    logout: 'Déconnexion',
    newSession: 'Nouvelle session',
    sessions: 'Sessions',
    allSessions: 'Toutes les sessions',
    clearAll: 'Tout effacer',
    resetAllData: 'Réinitialiser toutes les données',
    resetView: 'Réinitialiser la vue',

    themeAriaLight: 'Passer en mode clair',
    themeAriaDark: 'Passer en mode sombre',
    themeTitleLight: 'Mode clair',
    themeTitleDark: 'Mode sombre',
    themeLabelLight: 'Clair',
    themeLabelDark: 'Sombre',
    
    // Financial Summary
    income: 'Revenus',
    expenses: 'Dépenses',
    payroll: 'Salaires',
    balance: 'Solde',
    
    // Income
    incomeTitle: 'Revenus',
    addIncome: 'Ajouter',
    noIncome: 'Aucun revenu enregistré',
    sales: 'Ventes',
    reservation: 'Réservations',
    
    // Expenses
    expensesTitle: 'Dépenses',
    addExpense: 'Ajouter',
    noExpenses: 'Aucune dépense enregistrée',
    bills: 'Factures (électricité, loyer...)',
    suppliers: 'Fournisseurs',
    payrollCategory: 'Salaires',
    other: 'Autre',
    
    // Modals
    addEmployeeTitle: 'Ajouter un employé',
    addIncomeTitle: 'Ajouter un revenu',
    addExpenseTitle: 'Ajouter une dépense',
    name: 'Nom',
    position: 'Poste',
    monthlySalary: 'Salaire mensuel (CHF)',
    socialContributions: 'Cotisations sociales (CHF)',
    date: 'Date',
    type: 'Type',
    amount: 'Montant (CHF)',
    description: 'Description',
    category: 'Catégorie',
    add: 'Ajouter',
    cancel: 'Annuler',
    
    // Types
    SALES: 'Ventes',
    RESERVATION: 'Réservations',
    BILLS: 'Factures',
    SUPPLIERS: 'Fournisseurs',
    PAYROLL: 'Salaires',
    OTHER: 'Autre',
    // Landing - Navbar
    navFeatures: 'Fonctionnalités',
    navHowItWorks: 'Comment ça marche',
    navModules: 'Modules',
    navPlatform: 'Plateforme',
    navPricing: 'Tarifs',
    navSecurity: 'Sécurité',
    navContact: 'Contact',
    navGetStarted: 'Commencer',
    navSwitchToFrench: 'Passer en français',
    navSwitchToEnglish: 'Passer en anglais',
    navChangeLanguage: 'Changer la langue',
    navTranslateEnglish: 'English',
    navTranslateFrench: 'Français',

    // Landing - Hero
    heroBadge: 'Concu pour la Suisse',
    heroTitleLine1: 'Vos finances,',
    heroTitleHighlight: 'automatisees',
    heroTitleLine2: 'avec la precision suisse',
    heroDescription:
      'Importez n\'importe quel document - facture, recu, fiche de paie - et laissez l\'IA extraire, categoriser et organiser vos donnees financieres. Revenus, depenses, salaires et rapports sur une seule plateforme.',
    heroStartTrial: 'Demarrer l\'essai gratuit',
    heroWatchDemo: 'Voir la demo',
    heroStatAccuracy: 'Precision OCR',
    heroStatSpeed: 'Traitement plus rapide',
    heroStatBusinesses: 'Entreprises',
    heroImageAlt:
      'Tableau de bord financier Paystack.ch affichant revenus, depenses, salaires et traitement IA des documents',
    heroDocumentProcessed: 'Document traite',
    heroExtractedAmount: "CHF 2'486.63 extrait",

    // Landing - Pricing
    pricingTitle: 'Tarifs',
    pricingHeadingStart: 'Tarification simple et',
    pricingHeadingHighlight: 'transparente',
    pricingDescription:
      'Tous les prix sont en CHF. Essai de 7 jours (carte enregistree), puis facturation recurrente. Evoluez au rythme de votre entreprise.',
    pricingMostPopular: 'Le plus populaire',
    pricingCurrency: 'CHF',
    pricingCustom: 'Sur mesure',
    pricingStarterAmount: '29.-',
    pricingBusinessAmount: '59.-',
    pricingUnlimitedAmount: '499.-',
    pricingPerMonth: '/mois',
    planStarterName: 'Starter',
    planStarterDescription:
      'Pour les freelances et entrepreneurs individuels qui debutent l\'automatisation financiere.',
    planBusinessName: 'Business',
    planBusinessDescription:
      'Pour les entreprises en croissance qui ont besoin d\'une gestion financiere complete avec acces equipe.',
    planUnlimitedName: 'Illimité',
    planUnlimitedDescription:
      'Pour les equipes a fort volume : tous les modules in-app, sans plafond de documents, rapports TVA complets et facturation autonome.',
    planEnterpriseName: 'Entreprise',
    planEnterpriseDescription:
      'Pour les grandes organisations necessitant des integrations personnalisees, un SLA et un support dedie.',
    planStarterFeature1: 'Traitement de documents (50/mois)',
    planStarterFeature2: 'Suivi revenus et depenses',
    planStarterFeature3: 'Totaux CHF sur le tableau de bord ; Rapports avec filtres, synthese mensuelle & export CSV',
    planStarterFeature4: '1 utilisateur',
    planStarterFeature5: 'Support email',
    planStarterFeature6: 'Jusqu\'a 2 sessions enregistrees (periodes comptables)',
    planBusinessFeature1: 'Traitement de documents (500/mois)',
    planBusinessFeature2: 'Onglet Revenus : POS / Z, paie & jusqu\'a 10 employes',
    planBusinessFeature3: 'Rapports PDF & TVA suisse (CSV/PDF, par mois ou annee)',
    planBusinessFeature4: 'Jusqu\'a 10 utilisateurs',
    planBusinessFeature5: 'Sessions illimitees + vue « Toutes les sessions »',
    planBusinessFeature6: 'Support prioritaire',
    planBusinessFeature7: 'Portail client Stripe (offre, carte, annulation)',
    planUnlimitedFeature1: 'Traitement de documents illimite',
    planUnlimitedFeature2: 'Utilisateurs illimites',
    planUnlimitedFeature3: 'Tous les modules (actuels + futurs)',
    planUnlimitedFeature4: 'Rapports PDF & TVA suisse complets (comme Business, sans plafond docs)',
    planUnlimitedFeature5: 'Sessions & employes illimites + vue « Toutes les sessions »',
    planUnlimitedFeature6: 'Facturation & changement d\'offre via Stripe (sans plafond docs)',
    planEnterpriseFeature1: 'Option marque blanche',
    planEnterpriseFeature2: 'Traitement de documents illimite',
    planEnterpriseFeature3: 'Integration personnalisee',
    planEnterpriseFeature4: 'Tous les modules (actuels + futurs)',
    planEnterpriseFeature5: 'Utilisateurs illimites',
    planEnterpriseFeature6: 'Responsable de compte dedie',
    planEnterpriseFeature7: 'SLA et garantie de disponibilite',
    planEnterpriseFeature8: 'Deploiement sur site (on-premise)',
    ctaStartTrial: 'Demarrer l\'essai gratuit',
    ctaContactSales: 'Contacter les ventes',

    // Landing - CTA section
    ctaSectionLabel: 'Commencer',
    ctaSectionHeadingStart: 'Pret a automatiser',
    ctaSectionHeadingHighlight: 'vos finances ?',
    ctaSectionDescription:
      'Rejoignez les entreprises suisses qui ont deja transforme leur gestion financiere. Essai 7 jours, puis abonnement simple.',
    ctaSectionBookDemo: 'Reserver une demo',
    ctaSectionTrust1: 'Essai 7 jours',
    ctaSectionTrust2: 'Paiement securise via Stripe',
    ctaSectionTrust3: 'Annulation a tout moment',
    ctaSectionContactUs: 'Contactez-nous',
    contactEmail: 'Email',
    contactPhone: 'Telephone',
    contactLocation: 'Adresse',
    contactCityCountry: 'Geneve, Suisse',
    swissMadeGeneva: 'Logiciel suisse - Geneve, CH',

    // Auth pages
    authTagline: 'Suivi financier',
    authSignInTitle: 'Connexion',
    authSignUpTitle: 'Creer un compte',
    authDisplayName: 'Nom affiche',
    authEmailLabel: 'E-mail',
    authPasswordLabel: 'Mot de passe',
    authContinueGoogle: 'Continuer avec Google',
    authSubmitSignIn: 'Se connecter',
    authSubmitSignUp: 'Creer mon compte',
    authAdminTitle: 'Connexion admin',
    authAdminDescription: 'Acces admin pour les operateurs Paystack.ch existants. Aucun paiement requis.',
    authAdminSubmit: 'Connexion admin',
    authAdminGoogle: 'Continuer en admin avec Google',
    authAdminUnauthorized: 'Ce compte n\'est pas configure comme admin Paystack.ch.',
    authAdminGateTitle: 'Acces operateur',
    authAdminGateDescription:
      'Saisissez le mot de passe serveur (ADMIN_ACCESS_PASSWORD sur Vercel) pour debloquer les outils de test des offres.',
    authAdminGatePasswordLabel: 'Mot de passe serveur',
    authAdminGateSubmit: 'Debloquer',
    authAdminGateLock: 'Verrouiller admin',
    authAdminPlanTestTitle: 'Ouvrir la caisse invite par offre',
    authAdminPlanLive: 'Stripe live (cles reelles)',
    authAdminPlanTest: 'Stripe test (cles test)',
    authAdminBypassSectionTitle: 'Admin Firebase (contournement abonnement)',
    authNeedAccount: 'Pas encore de compte ?',
    authSignUpLink: 'S\'inscrire',
    authHaveAccount: 'Deja un compte ?',
    authSignInLink: 'Se connecter',
    authBackHome: 'Retour a l\'accueil',
    authFooterSecure: 'Acces securise — vos donnees vous appartiennent',
    authWorking: 'Patience…',
    authFirebaseMissingShort: 'Firebase n\'est pas configure. Ajoutez les variables VITE_FIREBASE_* a votre environnement.',
    checkoutSameEmailNote:
      'Paiement enregistre. Creez votre compte avec le meme e-mail qu\'a la caisse Stripe pour lier l\'abonnement a cette connexion.',
    navSignInExisting: 'Connexion admin',
    checkoutLinkErrorTitle: 'Impossible de lier l\'abonnement',
    checkoutTryAgain: 'Reessayer',
    checkoutContinueWithoutLink: 'Continuer vers l\'app',

    startTrialTitle: 'Demarrer l\'essai de 7 jours',
    startTrialSubtitle: 'Paiement securise',
    startTrialBody:
      'Ajoutez un moyen de paiement pour demarrer l\'essai. La facturation commence apres l\'essai sauf annulation dans le portail client. Puis creez un compte ou connectez-vous avec le meme e-mail.',
    startTrialBillingNote:
      'Utilisez le meme e-mail pour Paystack.ch qu\'a la caisse Stripe pour lier correctement l\'abonnement.',
    startTrialCta: 'Continuer vers le paiement securise',
    startTrialSignIn: 'Vous avez deja un compte ?',
    startTrialRedirecting: 'Redirection vers le paiement securise…',
    startTrialCheckoutCancelled: 'Paiement annule',
    startTrialCheckoutCancelledHint: 'Retournez a l\'accueil ou relancez la caisse pour cette offre.',
    startTrialGoHome: 'Retour a l\'accueil',
    startTrialRetry: 'Relancer la caisse',

    subscriptionLoading: 'Verification de l\'abonnement…',
    subscriptionTitle: 'Abonnez-vous pour continuer',
    subscriptionBody:
      'Cet espace necessite un abonnement actif. Demarrez un essai de 7 jours (carte requise), puis facturation automatique a la fin de l\'essai sauf annulation dans le portail Stripe.',
    subscriptionCta: 'Essai 7 jours et abonnement',
    subscriptionUpdatePayment: 'Mettre a jour le moyen de paiement',
    subscriptionTrialUntil: 'Essai jusqu\'au {date}',
    subscriptionManageBilling: 'Facturation et offre',
    subscriptionPickPlan: 'Choisissez une offre',
    subscriptionEnterpriseHint: 'Entreprise (tarif sur mesure) : contactez info@paystack.ch.',
    subscriptionPickPlanError: 'Choisissez Starter, Business ou Illimite avant le paiement.',
    planLimitDocuments: 'Plafond mensuel de traitement de documents atteint ({n} termines ce mois-ci). Passez a une offre superieure pour continuer.',
    planLimitSessions: 'Votre offre autorise au plus {n} periodes comptables (sessions). Passez a une offre superieure pour en ajouter.',
    planLimitEmployees: 'Votre offre autorise au plus {n} employe(s). Passez a une offre superieure pour en ajouter.',
    reportsAdvancedLocked: 'Les exports PDF avances et les declarations TVA suisses necessitent l\'offre Business ou superieure.',

    planSummaryTitle: 'Votre abonnement',
    planSummaryPlanUnknown: 'Offre',
    planSummaryUnlimited: 'Illimite',
    planSummaryStatusTrialing: 'Essai',
    planSummaryStatusActive: 'Actif',
    planSummaryDocuments: 'Documents / mois',
    planSummaryEmployees: 'Places equipe',
    planSummarySessions: 'Sessions enregistrees',
    planSummaryFlagBasicReports: 'Rapports & CSV',
    planSummaryFlagAdvanced: 'Analyses avances & reporting suisse',
    planSummaryFlagAllModules: 'Tous les modules principaux',
    planSummaryFlagApi: 'Acces API',
    planSummaryFlagPriority: 'Support prioritaire',

    authDividerEmail: 'E-mail',
    authPlaceholderAdminEmail: 'admin@paystack.ch',
    authPlaceholderEmail: 'vous@entreprise.ch',
    authPlaceholderDisplayName: 'Marie Mueller',
    authErrorPrefix: 'Erreur : ',

    footerTagline:
      'Gestion financiere assistee par IA, avec precision suisse. Deja adopte par des entreprises en Suisse.',
    footerSwissSoftware: 'Logiciel suisse',
    footerCopyright: 'Paystack.ch — Tous droits reserves.',
    footerTrustGdpr: 'Conforme RGPD',
    footerTrustSwissDp: 'Protection des donnees suisse',
    footerTrustSoc2: 'Pret SOC 2',
    footerColProduct: 'Produit',
    footerColCompany: 'Entreprise',
    footerColResources: 'Ressources',
    footerColLegal: 'Mentions legales',
    footerProduct1: 'Fonctionnalites',
    footerProduct2: 'Tarifs',
    footerProduct3: 'Modules',
    footerProduct4: 'Feuille de route',
    footerProduct5: 'Journal des versions',
    footerCompany1: 'A propos',
    footerCompany2: 'Carrieres',
    footerCompany3: 'Blog',
    footerCompany4: 'Dossier de presse',
    footerResources1: 'Documentation',
    footerResources2: 'Reference API',
    footerResources3: 'Centre d\'aide',
    footerResources4: 'Communaute',
    footerLegal1: 'Politique de confidentialite',
    footerLegal2: 'Conditions d\'utilisation',
    footerLegal3: 'Traitement des donnees',
    footerLegal4: 'Mentions legales',

    landingSection01Label: 'Fonctions cles',
    landingFeaturesTitle1: 'Tout ce qu\'il faut pour',
    landingFeaturesTitleItalic: 'piloter vos finances',
    landingFeaturesSubtitle:
      'Six modules puissants automatisent vos operations financieres. Activez seulement ce dont votre entreprise a besoin.',
    landingFeat1Title: 'Traitement IA des documents',
    landingFeat1Desc:
      'Importez factures, recus, releves bancaires ou fiches de paie dans tout format. Notre IA extrait les donnees avec plus de 95 % de precision, categorise automatiquement et detecte les doublons — du papier aux donnees structurees en secondes.',
    landingFeat1S1L: 'Precision',
    landingFeat1S1V: '95 %+',
    landingFeat1S2L: 'Formats',
    landingFeat1S2V: 'PDF, JPG, PNG',
    landingFeat1S3L: 'Traitement',
    landingFeat1S3V: '3x en parallele',
    landingFeat2Title: 'Suivi des revenus',
    landingFeat2Desc:
      'Suivez chaque source de revenu — ventes quotidiennes, honoraires, abonnements, commissions. Creation automatique depuis les documents avec tableau de bord en temps reel et organisation par periode.',
    landingFeat2S1L: 'Categories',
    landingFeat2S1V: 'Illimite',
    landingFeat2S2L: 'Mises a jour',
    landingFeat2S2V: 'Temps reel',
    landingFeat2S3L: 'Sources',
    landingFeat2S3V: 'Auto + manuel',
    landingFeat3Title: 'Gestion des depenses',
    landingFeat3Desc:
      'Suivi multi-categories par fournisseur. Du loyer aux charges, paie et marketing — chaque franc est comptabilise avec creation automatique depuis les documents importes.',
    landingFeat3S1L: 'Categories',
    landingFeat3S1V: '12+ integrees',
    landingFeat3S2L: 'Suivi',
    landingFeat3S2V: 'Par fournisseur',
    landingFeat3S3L: 'Export',
    landingFeat3S3V: 'Excel + PDF',
    landingFeat4Title: 'Paie et salaires',
    landingFeat4Desc:
      'Traitement des fiches de paie au format suisse (AVS, LPP, AC). Suivi brut/net, detail des deductions et syntheses mensuelles automatiques.',
    landingFeat4S1L: 'Format',
    landingFeat4S1V: 'Suisse (AVS/LPP)',
    landingFeat4S2L: 'Deductions',
    landingFeat4S2V: 'Personnalisables',
    landingFeat4S3L: 'Rapports',
    landingFeat4S3V: 'Mensuel',
    landingFeat5Title: 'Sessions et periodes',
    landingFeat5Desc:
      'Periodes comptables illimitees — jour, semaine, mois, trimestre ou projet. Basculez instantanement, isolez les donnees et generez des rapports par periode.',
    landingFeat5S1L: 'Periodes',
    landingFeat5S1V: 'Illimite',
    landingFeat5S2L: 'Types',
    landingFeat5S2V: '7+ options',
    landingFeat5S3L: 'Bascule',
    landingFeat5S3V: 'Instantanee',
    landingFeat6Title: 'Rapports et analyses',
    landingFeat6Desc:
      'Analyse mensuelle des revenus, revenus vs depenses, principaux fournisseurs, filtres avances. Export PDF pret a imprimer ou CSV avec piste d\'audit pour la conformite.',
    landingFeat6S1L: 'Types de rapports',
    landingFeat6S1V: '7+',
    landingFeat6S2L: 'Filtres',
    landingFeat6S2V: 'Avances',
    landingFeat6S3L: 'Export',
    landingFeat6S3V: 'CSV + PDF',

    landingHowLabel: 'Comment ca marche',
    landingHowTitle1: 'Du papier aux',
    landingHowTitleHighlight: 'donnees structurees',
    landingHowTitleSub: 'en quatre etapes simples',
    landingHowStep1Title: 'Importer',
    landingHowStep1Sub: 'Capturer tout document',
    landingHowStep1Desc:
      'Photo, PDF ou glisser-deposer. Factures, recus, releves, fiches de paie — nous les traitons tous.',
    landingHowStep2Title: 'Extraire',
    landingHowStep2Sub: 'L\'IA lit et comprend',
    landingHowStep2Desc:
      'Notre moteur traite le document avec plus de 95 % de precision OCR : montants, dates, fournisseurs, categories et lignes automatiquement.',
    landingHowStep3Title: 'Verifier',
    landingHowStep3Sub: 'Donnees organisees et validees',
    landingHowStep3Desc:
      'Revisez dans une interface claire. Modifiez si besoin, validez — le systeme classe en revenus, depenses ou paie.',
    landingHowStep4Title: 'Rapporter',
    landingHowStep4Sub: 'Pret pour vos outils',
    landingHowStep4Desc:
      'Tableaux de bord en temps reel, rapports, export Excel ou PDF. Donnees structurees, consultables et pretes pour l\'audit.',
    landingHowScreenshotAlt: 'Paystack.ch — tableau de bord et traitement des documents',

    landingTrustedLabel: 'Utilise dans tous les secteurs',
    landingTrustedInd1: 'Commerce de detail',
    landingTrustedInd2: 'Restauration et hotellerie',
    landingTrustedInd3: 'Services professionnels',
    landingTrustedInd4: 'Conseil et freelance',
    landingTrustedInd5: 'Industrie',
    landingTrustedInd6: 'Sante',
    landingTrustedInd7: 'E-commerce',
    landingTrustedInd8: 'Education',

    landingModulesLabel: 'Architecture modulaire',
    landingModulesTitle1: 'Activez ce que vous',
    landingModulesTitleItalic: 'utilisez vraiment',
    landingModulesSubtitle:
      'Chaque entreprise est differente. Activez uniquement les modules necessaires — du traitement documentaire a la gestion financiere complete.',
    landingModulesTabCore: 'Coeur',
    landingModulesTabEnhanced: 'Etendu',
    landingModuleStatusLive: 'Actif',
    landingModuleStatusPartial: 'Partiel',
    landingModuleStatusSoon: 'Bientot',
    landingModCore1Name: 'Traitement des documents',
    landingModCore1Desc: 'Extraction assistee par IA depuis tout format',
    landingModCore2Name: 'Suivi des revenus',
    landingModCore2Desc: 'Suivi multi-categories avec creation automatique',
    landingModCore3Name: 'Gestion des depenses',
    landingModCore3Desc: 'Classification par fournisseur',
    landingModCore4Name: 'Paie et salaires',
    landingModCore4Desc: 'Fiches de paie suisses (AVS/LPP)',
    landingModCore5Name: 'Gestion des sessions',
    landingModCore5Desc: 'Periodes comptables illimitees, bascule instantanee',
    landingModCore6Name: 'Rapports et analyses',
    landingModCore6Desc: 'Rapports financiers complets avec exports',
    landingModEnh1Name: 'Bibliotheque documentaire',
    landingModEnh1Desc: 'Archives par entite avec recherche et filtres',
    landingModEnh2Name: 'Module POS',
    landingModEnh2Desc: 'Saisie Z avec extraction IA ; POS complet a venir',
    landingModEnh3Name: 'Inventaire',
    landingModEnh3Desc: 'Stock FIFO/LIFO et codes-barres',
    landingModEnh4Name: 'Gestion des employes',
    landingModEnh4Desc: 'Profils, presence et conges',
    landingModEnh5Name: 'Gestion des fournisseurs',
    landingModEnh5Desc: 'Profils, conditions et suivi de performance',
    landingModEnh6Name: 'Generation de factures',
    landingModEnh6Desc: 'Modeles, numerotation automatique et factures recurrentes',
    landingModulesScreenshotAlt: 'Paystack.ch — rapports financiers et analyses',

    landingBizLabel: 'Presets par secteur',
    landingBizTitle1: 'Configure pour',
    landingBizTitleHighlight: 'votre secteur',
    landingBizSubtitle:
      'Configurations predefinies par type d\'activite. Partez d\'un modele metier, puis adaptez les modules a votre flux reel.',
    landingBiz1Name: 'Commerce de detail',
    landingBiz1Mods: 'POS, Inventaire, Revenus, Depenses, Fournisseurs',
    landingBiz1Desc: 'Suivi des ventes, stocks et fournisseurs pour les magasins.',
    landingBiz2Name: 'Restaurants et cafes',
    landingBiz2Mods: 'POS, Revenus, Depenses, Paie, Fournisseurs',
    landingBiz2Desc: 'Z de caisse, chiffre du jour et paie du personnel.',
    landingBiz3Name: 'Services professionnels',
    landingBiz3Mods: 'Revenus, Depenses, Paie, Projets, Facturation',
    landingBiz3Desc: 'Comptabilite par projet, facturation clients et prestataires.',
    landingBiz4Name: 'Conseil et freelance',
    landingBiz4Mods: 'Revenus, Depenses, Clients, Projets, Facturation',
    landingBiz4Desc: 'Periodes par client, rentabilite projet et facturation.',
    landingBiz5Name: 'Industrie',
    landingBiz5Mods: 'Depenses, Paie, Inventaire, Fournisseurs, Employes',
    landingBiz5Desc: 'Matiere premiere, couts de production et main-d\'oeuvre.',
    landingBiz6Name: 'E-commerce',
    landingBiz6Mods: 'Revenus, Depenses, Inventaire, Fournisseurs, Integrations',
    landingBiz6Desc: 'Revenus multi-canal, synchro stock et integrations.',
    landingBiz7Name: 'Sante',
    landingBiz7Mods: 'Revenus, Depenses, Paie, Employes, Documents',
    landingBiz7Desc: 'Facturation patients, equipe et archivage conforme.',
    landingBiz8Name: 'Education',
    landingBiz8Mods: 'Revenus, Depenses, Paie, Employes, Rapports',
    landingBiz8Desc: 'Scolarite, paie du personnel et rapports par periode.',

    landingPlatformLabel: 'Visite de la plateforme',
    landingPlatformTitle1: 'Voyez-la',
    landingPlatformTitleItalic: 'en action',
    landingPlatformSubtitle:
      'Vraies captures d\'un deploiement en production — pas de maquettes. La plateforme utilisee aujourd\'hui par des entreprises suisses.',
    landingPlatformV1Label: 'Tableau de bord',
    landingPlatformV1Title: 'Vue financiere en un coup d\'oeil',
    landingPlatformV1Desc:
      'Revenus, depenses, salaires et solde en temps reel. Import de documents, suivi du traitement et TVA dans une vue unifiee.',
    landingPlatformV1Alt:
      'Paystack.ch — tableau de bord avec revenus, depenses, salaires, TVA et file d\'attente des documents',
    landingPlatformV2Label: 'Revenus et POS',
    landingPlatformV2Title: 'Suivi des revenus et Z de caisse',
    landingPlatformV2Desc:
      'Tous les flux de revenus avec Z generees depuis les donnees quotidiennes. Saisie manuelle, photo et generation IA avec TVA suisse (7,7 %) et repartition des paiements.',
    landingPlatformV2Alt:
      'Paystack.ch — module Revenus avec generation Z, saisie manuelle et import photo',
    landingPlatformV3Label: 'Rapports',
    landingPlatformV3Title: 'Analyse mensuelle des revenus',
    landingPlatformV3Desc:
      'Filtres par periode, categorie ou fournisseur. Bilan mensuel revenus vs depenses avec solde. Export CSV ou PDF pour votre comptable.',
    landingPlatformV3Alt:
      'Paystack.ch — rapports mensuels avec revenus, depenses et solde par periode',
    landingPlatformV4Label: 'Documents',
    landingPlatformV4Title: 'Bibliotheque organisee',
    landingPlatformV4Desc:
      'Documents par fournisseur, employe ou rapport POS. Comptes et montants par entite. Recherche, filtres et historique complet.',
    landingPlatformV4Alt:
      'Paystack.ch — bibliotheque avec cartes fournisseur et totaux en CHF',
    landingPlatformWlTitle: 'Pret pour marque blanche',
    landingPlatformWlBody:
      'Chaque deploiement peut etre adapte — logo, couleurs et domaine. Cet exemple montre un deploiement live pour Cafe de la Place.',

    landingSecurityLabel: 'Securite et conformite',
    landingSecurityTitle1: 'Securite aux',
    landingSecurityTitleHighlight: 'standards suisses',
    landingSecuritySubtitle:
      'Vos donnees financieres meritent une protection de niveau bancaire. Securite entreprise et precision suisse.',
    landingSec1Title: 'Chiffrement de bout en bout',
    landingSec1Desc: 'Donnees chiffrees en transit et au repos (normes AES-256).',
    landingSec2Title: 'Acces par roles',
    landingSec2Desc: 'Permissions fines : chaque membre ne voit que le necessaire.',
    landingSec3Title: 'Journal d\'audit',
    landingSec3Desc: 'Chaque action horodatee pour la tracabilite et la conformite.',
    landingSec4Title: 'Hebergement en Suisse',
    landingSec4Desc: 'Vos donnees restent en Suisse, conformes a la LPD.',
    landingSec5Title: 'Sauvegardes automatiques',
    landingSec5Desc: 'Sauvegardes continues et reprise apres sinistre.',
    landingSec6Title: 'Conforme RGPD',
    landingSec6Desc: 'Conformite europeenne et suisse (RGPD / LPD).',

    landingMobileLabel: 'Application mobile',
    landingMobileTitle1: 'Vos finances,',
    landingMobileTitleItalic: 'dans votre poche',
    landingMobileSubtitle:
      'L\'app Paystack.ch apporte la gestion financiere sur mobile. Scannez un recu, consultez le tableau de bord et validez les depenses partout.',
    landingMobileF1Label: 'Photo et import',
    landingMobileF1Desc: 'Photographiez un document et traitez-le instantanement',
    landingMobileF2Label: 'Notifications push',
    landingMobileF2Desc: 'Alertes en temps reel pour documents et rapports',
    landingMobileF3Label: 'Mode hors ligne',
    landingMobileF3Desc: 'Capture hors ligne ; synchronisation au retour reseau',
    landingMobileF4Label: 'Experience native',
    landingMobileF4Desc: 'Apps iOS et Android avec connexion biométrique',
    landingMobileCta: 'Rejoindre la liste d\'attente',
    landingMobileTarget: 'Objectif : T3 2026',

    landingRoadmapLabel: 'Feuille de route',
    landingRoadmapTitle1: 'Construit pour le',
    landingRoadmapTitleHighlight: 'long terme',
    landingRoadmapSubtitle:
      'Notre feuille de route evolue avec les besoins clients. De l\'essentiel a l\'entreprise, nous batissons une plateforme complete.',
    landingRoadP1Label: 'Phase 1',
    landingRoadP1Title: 'Fonctions de base',
    landingRoadP1I1: 'Traitement des documents',
    landingRoadP1I2: 'Suivi revenus et depenses',
    landingRoadP1I3: 'Gestion des sessions',
    landingRoadP1I4: 'Rapports de base',
    landingRoadP1I5: 'Authentification',
    landingRoadP2Label: 'Phase 2',
    landingRoadP2Title: 'Fonctions etendues',
    landingRoadP2I1: 'Analyses avancees',
    landingRoadP2I2: 'Suivi d\'inventaire',
    landingRoadP2I3: 'Gestion des employes',
    landingRoadP2I4: 'Gestion des fournisseurs',
    landingRoadP3Label: 'Phase 3',
    landingRoadP3Title: 'Fonctions avancees',
    landingRoadP3I1: 'Gestion clients',
    landingRoadP3I2: 'Gestion de projets',
    landingRoadP3I3: 'Generation de factures',
    landingRoadP3I4: 'Applications mobiles',
    landingRoadP4Label: 'Phase 4',
    landingRoadP4Title: 'Fonctions entreprise',
    landingRoadP4I1: 'Multi-entites',
    landingRoadP4I2: 'Integrations avancees',
    landingRoadP4I3: 'Workflows personnalises',
    landingRoadP4I4: 'Marketplace d\'APIs',

    dashFinancialTracking: 'Suivi financier',
    dashSwitchClientTitle: 'Changer de client',
    dashSignOutTitle: 'Deconnexion',
    dashTabReconciliation: 'Rapprochement',
    dashTabInsights: 'Analyses',
    dashTitleReconciliation: 'Tableau de rapprochement',
    dashTitleInsights: 'Analyses financieres',
    dashSubtitleAudit: 'Extraction automatisee pour le rapprochement financier.',
    dashSubtitleInsights: 'Analyse multi-modale sur donnees auditees.',
    dashFooterCopyright: 'Cafe de la Place • Suivi financier',
    dashFooterZ2: 'Traitement Z2',
    dashFooterAuditTrail: 'Piste d\'audit',

    onboardLoading: 'Chargement des clients…',
    onboardSubtitle: 'Selectionnez ou ajoutez un client',
    onboardHeading: 'Client',
    onboardNewClientLabel: 'Nom du nouveau client',
    onboardPlaceholder: 'ex. Acme SA',
    onboardAdd: 'Ajouter',
    onboardSelectExisting: 'Ou selectionnez un client existant',
    onboardErrorAddClient: 'Impossible d\'ajouter le client. Verifiez les regles Firestore ou la console.',

    firebaseMissingTitle: 'Configuration Firebase manquante',
    firebaseMissingBody:
      'Cette application necessite VITE_FIREBASE_* cote frontend et GEMINI_API_KEY uniquement sur le serveur API.',
    firebaseMissingNetlifyHeading: 'Sur Netlify',
    firebaseMissingNetlifyBody:
      'Parametres du site → Variables d\'environnement → ajoutez les cles du fichier .env.example, puis redeployez.',
    firebaseMissingLocalHeading: 'En local',
    firebaseMissingLocalBody: 'Copiez .env.example vers .env.local et renseignez les valeurs.',
    firebaseMissingCta: 'Ouvrir la console Firebase',

    emailVerifyTitle: 'Verification de l\'e-mail',
    emailVerifyBody: 'Votre compte e-mail / mot de passe n\'est pas encore verifie.',
    emailVerifySentPrefix: 'Un message a ete envoye a',
    emailVerifyResend: 'Renvoyer l\'e-mail de verification',
    emailVerifyResending: 'Envoi…',
    emailVerifySignOut: 'Deconnexion',
    emailVerifySuccess: 'E-mail de verification envoye. Consultez votre boite, puis rechargez la page.',

    fiEvidenceMeta: 'Metadonnees de preuve d\'audit',
    fiOpenTraceTab: 'Ouvrir la trace dans un nouvel onglet',
    fiControlMeta: 'Metadonnees de controle',
    fiClassification: 'Classification',
    fiFiscalDate: 'Date fiscale',
    fiGrossValue: 'Valeur brute',
    fiComplianceAlerts: 'Alertes de conformite',
    fiAuditIntegrity: 'Integrite d\'audit validee',
    fiAiInterpretation: 'Note d\'interpretation IA',
    fiNoInterpretation: 'Aucune trace d\'interpretation diagnostique pour cet actif d\'audit.',
    fiCloseRecord: 'Fermer l\'enregistrement',
    fiIncomeLabel: 'Entrees',
    fiExpenseLabel: 'Sorties',
    fiLineCountLabel: 'Nombre de lignes d\'audit',
    fiAssetsSuffix: 'ACTIFS',
    fiRecoStatusLabel: 'Statut de rapprochement',
    fiCertified: 'CERTIFIE',
    fiDynamicDist: 'Repartition dynamique',
    fiForensicHub: 'Hub neuronal forensique',
    fiDataIntegration: 'Integration des donnees',
    fiCustomTaxonomy: 'Taxonomie personnalisee',
    fiChatEmptyTitle: 'Moteur neuronal initialise',
    fiChatEmptyHint: 'Interrogez anomalies, categories ou rapprochement d\'audit',
    fiAnalyzing: 'Execution de l\'analyse…',
    fiInputPlaceholder: 'Interrogez le jeu de donnees audite ou joignez une preuve visuelle…',
    fiUncategorized: 'Non classe',
    fiCategoryBank: 'Banque',
    fiUnknownEntity: 'Entite inconnue',
    fiAuditVisionScan: '[Scan vision audit]',
    fiModelFailed: 'Pas de reponse.',
    fiDiagnosticError: 'Erreur de diagnostic : ',
    fiNa: 'N/D',

    bankWorkbenchTitle: 'Etabli de rapprochement',
    bankWorkbenchSubtitle: 'Appariement automatise avec preuves d\'audit.',
    bankUploadLabel: 'Importer des releves pour liaison par lot',
    bankStopLinking: 'Arreter la liaison',
    bankStopping: 'Arret…',
    bankTurboLinking: 'Liaison turbo',
    bankWorkersDraining: 'Vidage des workers',
    bankWorkersActive: '6 workers actifs',
    bankQueueTitle: 'File des releves',
    bankMoneyIn: 'Entrees',
    bankMoneyOut: 'Sorties',
    bankNetCashFlow: 'Flux de tresorerie net',
    bankThDate: 'Date',
    bankThDesc: 'Description',
    bankThAmount: 'Montant',
    bankThLinking: 'Liaison d\'audit',
    bankNone: 'Aucune',
    bankSelectCompleted: 'Selectionnez une analyse terminee',
    bankNotifHalting: 'Arret du rapprochement…',
    bankVerifiedPrefix: 'Verifie : ',
    bankStatus_pending: 'en attente',
    bankStatus_processing: 'en cours',
    bankStatus_completed: 'termine',
    appLoading: 'Chargement…',
    bankStatus_error: 'erreur',
  },
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

const LANGUAGE_STORAGE_KEY = 'paystack_language';

/** First visit defaults to French; English only when localStorage is explicitly `paystack_language=en`. */
function readStoredLanguage(): Language {
  if (typeof window === 'undefined') return 'fr';
  try {
    const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (stored === 'en') return 'en';
    if (stored === 'fr') return 'fr';
  } catch {
    /* ignore */
  }
  return 'fr';
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  // Default French on first visit; navbar toggles EN/FR. User choice persists for return visits.
  const [language, setLanguageState] = useState<Language>(() => readStoredLanguage());

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      if (typeof window !== 'undefined') {
        window.localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
      }
    } catch {
      /* ignore */
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
